### ISSUE TITLE
File content should not be expanded during import

### ISSUE THREAD

**Issue by yujunz** [corneliusweig/konfig#21]
`kubectl konfig import --save ~/.kube/foo.config` seems expanding the content of file which is not expected.

```
# foo.config
users:
- name: vault-user
  user:
    client-certificate: client.crt
    client-key: client
```

is imported as

```
users:
- name: vault-user
  user:
    client-certificate: <content of client.crt>
    client-key: <content of client>
```

This is not expected since the certs generated by vault are temporary. It would be better to import it as is (the filename).
